- src/q7/ia-LINGI2261/ia-LINGI2261.tex
> AI synthesis completion

- src/q7/ia-LINGI2261/ia-LINGI2261.tex
Salut,
Quelques corrections et améliorations dans la synthese et aussi un debut de chapitre 10. 
C'est un gros commit de bourin mais j'avais oublié de forker :)
> correction + amelioration + chapitre 10 esquisse

- src/q7/ia-LINGI2261/ia-LINGI2261.tex
reste quelques petits points à compléter pour être vraiment précis
> chapitre 10 fin

- add.sh
- templates/Makefile
- templates/mk.mk
- templates/tex.tex
Utilisé pour créer proprement un cour dans l'arborescence
> Ajout du script add.sh

- src/q6/telecom/summary/telecom-summary.tex
> Minor changes

- src/q4/sigsys/summary/sigsys-summary.tex
+ Properties of the ROC
+ Corrections
> Try to improve explanation about feedback

- src/q1/elec-FSAB1201/elec-FSAB1201.mk
- src/q1/elec-FSAB1201/exam/2015/2015.mk
- src/q1/elec-FSAB1201/exam/2015/Janvier/All/Makefile
- src/q1/elec-FSAB1201/exam/2015/Janvier/All/elec-FSAB1201-exam-2015-Janvier-All.tex
- src/q1/elec-FSAB1201/exam/2015/Janvier/Janvier.mk
- src/q1/elec-FSAB1201/exam/exam.mk
- src/q1/q1.mk
J'ai également réparé les `.mk` qui foiraient dans q1
> elec-FSAB1201-exam-2015-Janvier-All

- src/q1/meca-FSAB1201/notes/Makefile
- src/q1/meca-FSAB1201/notes/meca-FSAB1201-notes.tex
- src/q1/meca-FSAB1201/summary/meca-FSAB1201-summary.tex
- nouveau document `notes` avec les démos importantes
- dans la synthèse, j'ai enlevé les démos et je fais référence au nouveau document
- dans la synthèse, j'ai ajouté rayon de scharzmachinbrol
> meca-FSAB1201: ajouté démonstrations

- src/q2/meca-FSAB1202/meca-FSAB1202.sty
- src/q2/meca-FSAB1202/notes/meca-FSAB1202-notes.tex
utilisation des commandes du .sty
> Mise en formes des notes de méca 2

- src/q3/chimie-FSAB1302/exam/2016/Août/All/chimie-FSAB1302-exam-2016-Août-All.tex
- src/q3/chimie-FSAB1302/exam/2016/Janvier/All/Makefile
- src/q3/chimie-FSAB1302/exam/2016/Janvier/All/chimie-FSAB1302-exam-2016-Janvier-All.tex
- src/q3/chimie-FSAB1302/exam/2016/Janvier/Janvier.mk
Voilà, normalement tout est propre maintenant, j'ai juste repris les fichiers soumis avant sans toucher à celui de 2015.
> Examen de chimie 2 (2016)

- src/q4/circmes-ELEC1370/summary/circmes-ELEC1370-summary.tex
Update quadriTab and some minor faults
> Update quadriTab and minor changes

- src/q4/coo-SINF1225/summary/coo-SINF1225-summary.tex
Pour le moment, il n'y a pas de changements dans la matière, même s'il faudrait un peu changer les figures (c'est moche et lourd ^^).
> Typos et corrections pour synthèse COO

- src/q4/sigsys-FSAB1106/exam/2015/Juin/All/sigsys-FSAB1106-exam-2015-Juin-All.tex
- src/q4/sigsys-FSAB1106/exam/2016/Juin/All/sigsys-FSAB1106-exam-2016-Juin-All.tex
- src/q4/sigsys-FSAB1106/exam/2017/2017.mk
- src/q4/sigsys-FSAB1106/exam/2017/Juin/All/Makefile
- src/q4/sigsys-FSAB1106/exam/2017/Juin/All/biblio.bib
- src/q4/sigsys-FSAB1106/exam/2017/Juin/All/sigsys-FSAB1106-exam-2017-Juin-All.tex
- src/q4/sigsys-FSAB1106/exam/2017/Juin/Juin.mk
Un ajout de correctif, et quelques modifications à des correctifs existants.
> Sigsys examens

- src/q5/logique-INGI1101/exam/2017/Août/All/Makefile
- src/q5/logique-INGI1101/exam/2017/Août/All/logique-INGI1101-exam-2017-Août-All.tex
- src/q5/logique-INGI1101/exam/2017/Août/Août.mk
Est ce que y'a juste moyen de le publier après la session?
> Exam Logique Aout 2017

- src/q5/logique-INGI1101/exam/2017/Novembre/All/Makefile
- src/q5/logique-INGI1101/exam/2017/Novembre/All/logique-INGI1101-exam-2017-Novembre-All.tex
- src/q5/logique-INGI1101/exam/2017/Novembre/Novembre.mk
Ajout des questions de l'interrogation de logique du novembre 2017
> Ajout de logique-INGI1101-exam-2017-Novembre-Question

- src/eplchem.sty
- src/q3/chimie-FSAB1302/exam/2015/Janvier/All/chimie-FSAB1302-exam-2015-Janvier-All.tex
- src/q3/info-FSAB1402/exam/2012/Janvier/All/info-FSAB1402-exam-2012-Janvier-All.tex
Just some things I noticed while studying, thought I'd fix with my newly found free time.
> Fixed typos and units on projet3/chimie2, added cycle janvier 2015 chimie 2

- src/q6/conv-ELEC1310/summary/conv-ELEC1310-summary.tex
> Fix typo conv-summary (closes #432)

- src/q6/calcu-INGI1123/mcq/QCM12.tex
Two justification that weren't done
> Fix TODO in calcu/qcm/QCM12

- src/eplcommon.sty
- src/q4/opti-INMA1702/exam/2011/2011.mk
- src/q4/opti-INMA1702/exam/2011/Juin/Juin.mk
- src/q4/opti-INMA1702/exam/2011/Juin/Majeure/Makefile
- src/q4/opti-INMA1702/exam/2011/Juin/Majeure/opti-INMA1702-exam-2011-Juin-Majeure.tex
- src/q4/opti-INMA1702/exam/exam.mk
- src/q4/opti-INMA1702/summary/opti-INMA1702-summary.tex
Il faudrait encore rajouter le graphe pour la question sur Wolfe mais je vois pas trop comment faire pour l'instant.
> Add examen d'opti Majeure Juin 2011

- src/q4/eco-FSAB1803/eco-FSAB1803.mk
- src/q4/eco-FSAB1803/exam/2016/2016.mk
- src/q4/eco-FSAB1803/exam/2016/Juin/All/Makefile
- src/q4/eco-FSAB1803/exam/2016/Juin/All/eco-FSAB1803-exam-2016-Juin-All.tex
- src/q4/eco-FSAB1803/exam/2016/Juin/Juin.mk
- src/q4/eco-FSAB1803/exam/exam.mk
Ajout d'une correction de l'examen de Juin 2016 en Eco. Le Makefile
d'Eco avait un problème de compilation avec l'include, je suppose
que ça vient de add.sh? En tout cas, sur Mac ça ne compilait pas.
J'ai encore eu ce problème avec Systinfo je crois.
> Added Eco Juin 2016, fix error in Eco Makefile

- src/q4/fem-MECA1120/test/2014/2014.mk
- src/q4/fem-MECA1120/test/2014/Avril/All/Makefile
- src/q4/fem-MECA1120/test/2014/Avril/All/fem-MECA1120-test-2014-Avril-All.tex
- src/q4/fem-MECA1120/test/2014/Avril/Avril.mk
- src/q4/fem-MECA1120/test/test.mk
Voici une correction (adaptée de celle qui était déjà sur le drive) de l'interrogatoire de fem d'avril 2014.
> Ajout de fem Avril 2014

- src/q3/chimie-FSAB1302/exam/2015/Janvier/All/chimie-FSAB1302-exam-2015-Janvier-All.tex
Ajout d'une réponse pour la question 2, ajout d'un graphe pour la question 3, formatting des QCMs.
> Corrections Chimie2 Janvier 2015

- add.sh
- templates/exam.tex
- templates/tex.tex
On ne doit voir `Create directory...` uniquement quand on crée un nouveau cours. Quand on crée un nouveau document dans un cours déjà existant, on ne doit voir que `Create subdirectory...`.
J'améliore les templates des .tex pour tenir compte de la langue du texte en 1e page:
FR pour tous les cours de Q1 à Q6
EN pour tous les cours de Q7 à Q8
C'est ennuyant de changer à chaque fois de EN à FR pour tous les cours de bac...
> Improve add.sh

- src/eplbase.cls
frenchb->french
Ajout de l'adresse mail officielle de l'EPL-Drive
> Change eplbase.cls

- add.sh
J'ai enlevé la possibilité de mettre Septembre car il n'y a que des dossiers `Août` sur le drive, ça évite ainsi de créer 2 dossiers pour un même examen. Je peux le remettre si ça dérange. =)
> Update description of add.sh

- src/q5/stat-FSAB1105/stat-FSAB1105.sty
- src/q5/stat-FSAB1105/summary/stat-FSAB1105-summary.tex
Relecture et correction de fautes dans la synthèse de probastat. Je n'ai
pas encore eu le cours du coup s'il y avait des erreurs mathématiques,
je suis sûrement passé par-dessus...
> Proofreading of probastat summary

- src/root.mk
Il faut lancer `make pvc` pour avoir cette feature. Devrait résoudre partiellement #316 .
> Add pvc to latexmk

- src/q4/sigsys-FSAB1106/exam/2017/Juin/All/sigsys-FSAB1106-exam-2017-Juin-All.tex
> Proofreading sigsys juin 2017

- src/q3/math-FSAB1103/exam/2018/Janvier/All/math-FSAB1103-exam-2018-Janvier-All.tex
> Update math 3 exam 2018 janvier: question 1

- README.md
The current image is attempting to open a dead link.
> Update Git image

- src/eplcommon.sty
- src/q3/math-FSAB1103/exam/2018/Août/All/Makefile
- src/q3/math-FSAB1103/exam/2018/Août/All/math-FSAB1103-exam-2018-Août-All.tex
- src/q3/math-FSAB1103/exam/2018/Août/Août.mk
> Add math 3 exam 2018 août

- src/q3/math-FSAB1103/exam/2016/Août/All/math-FSAB1103-exam-2016-Août-All.tex
- src/q3/math-FSAB1103/exam/2017/Janvier/All/math-FSAB1103-exam-2017-Janvier-All.tex
Correction of minor inconsequential mistakes.
> Small correction in math 3 exams.

- src/q6/mft-MECA1321/exam/2018/Juin/Majeure/mft-MECA1321-exam-2018-Juin-Majeure.tex
Oups... :disappointed_relieved:
> Change min to maj

- add.sh
> Add.sh: fix issue #586

- src/q4/opti-INMA1702/notes/Makefile
- src/q4/opti-INMA1702/notes/cm/cm1-problemes.tex
- src/q4/opti-INMA1702/notes/opti-INMA1702-notes.tex
Un début d'une idée que j'avais, mais en voyant les CMs suivants, je ne suis pas sûr d'être en mesure de faire beaucoup plus (`tikz` c'est dur...). Peu importe, voici un début d'une MWIP (maybe work in progress).
> Add cm1 and main file to opti q4 notes

- src/q4/opti-INMA1702/notes/cm/cm1-problemes.tex
- src/q4/opti-INMA1702/notes/cm/cm2-formes.tex
- src/q4/opti-INMA1702/notes/opti-INMA1702-notes.tex
- src/q4/opti-INMA1702/summary/opti-INMA1702-summary.tex
3 changes:
- added the second lecture to the opti q4 notes;
- some minor fixes in the first lecture;
- made the norms appendix a bit prettier in the options q4 summary.
> Added a part of opti q4 notes

- src/q4/fem-MECA1120/summary/biblio.bib
- src/q4/fem-MECA1120/summary/fem-MECA1120-summary.tex
- src/q4/fem-MECA1120/test/2014/Avril/All/fem-MECA1120-test-2014-Avril-All.tex
> Work on fem summary, small fixes to fem test

- add.sh
- course_link.py
- templates/exam.tex
As discussed in the thread of a previous PR (#584).
Comme ceci: Closes #589
> Insert directly the course name in hypertitle when using add.sh

- src/q3/chimie-FSAB1302/exam/2014/Janvier/All/chimie-FSAB1302-exam-2014-Janvier-All.tex
- src/q3/chimie-FSAB1302/summary/chimie-FSAB1302-summary.tex
@Peiffap , je crois que tu as mis des `\begin{breqn}` alors qu'ils n'existent pas dans le package.
A vérifier, ces changements enlèvent les erreurs de compilation (encore...). :wink:
> [FSAB1302] Fix compilation errors

- src/q5/stat-FSAB1105/exam/2017/Janvier/All/stat-FSAB1105-exam-2017-Janvier-All.tex
E[Y] = 8/6 => E[Gain] = 18*8/6 - 20 = 24 - 20 = 4
> [LFSAB1105] Janvier 2017 - corrected final value of 2.1

- src/q5/stat-FSAB1105/exam/2017/Janvier/All/stat-FSAB1105-exam-2017-Janvier-All.tex
Added the full details since I stucked there a bit
> [LFSAB1105] janvier 2017 - More details for question 4.3

- src/q3/info-FSAB1402/exam/2013/Janvier/All/Q2-sol.oz
- src/q3/info-FSAB1402/exam/2013/Janvier/All/info-FSAB1402-exam-2013-Janvier-All.tex
- src/q3/info-FSAB1402/exam/2018/2018.mk
- src/q3/info-FSAB1402/exam/2018/Janvier/All/Makefile
- src/q3/info-FSAB1402/exam/2018/Janvier/All/info-FSAB1402-exam-2018-Janvier-All.tex
- src/q3/info-FSAB1402/exam/2018/Janvier/All/src/q2-sol.oz
- src/q3/info-FSAB1402/exam/2018/Janvier/All/src/q2.oz
- src/q3/info-FSAB1402/exam/2018/Janvier/Janvier.mk
Un examen que j'avais loupé.
Je rajouterai peut-être des corrections lorsque celui d'août aura eu lieu (demain).
> [FSAB1402] Exam: Add info 2 exam 2018 janvier and update sol of 2013 janvier

- src/config.yml
- src/q7/converto2-ELEC2313/converto2-ELEC2313.mk
- src/q7/converto2-ELEC2313/exam/2019/2019.mk
- src/q7/converto2-ELEC2313/exam/2019/Janvier/All/Makefile
- src/q7/converto2-ELEC2313/exam/2019/Janvier/All/converto2-ELEC2313-exam-2019-Janvier-All.tex
- src/q7/converto2-ELEC2313/exam/2019/Janvier/Janvier.mk
- src/q7/converto2-ELEC2313/exam/exam.mk
> [ELEC2313] Add exam January 2019

- src/q3/chimie-FSAB1302/exam/2016/Janvier/All/chimie-FSAB1302-exam-2016-Janvier-All.tex
> [LFSAB1302] Jan 2016: Fix rounding error and typo

- src/q6/introtelecom-ELEC1930/summary/introtelecom-ELEC1930-summary.tex
- src/q6/introtelecom-ELEC1930/summary/questions-icampus.tex
J'ai réactualisé l'introduction en ajoutant de nouveaux éléments.
Les liens bibliographiques n'étaient pas non plus corrects (les 'é' étaient notés avec l'encodage ASCII du coup pas moyen d'utiliser les liens tel quel).
Corrigé certaines fautes d'orthographes
> [ELEC1930] - Réactualisation de l'introduction + liens bib

- src/q4/opti-INMA1702/summary/opti-INMA1702-summary.tex
Dans une énumération on peut soit faire une phrase continue (auquel cas les points-virgules sont les bienvenus et les majuscules en début de point sont proscrites), soit faire différentes phrases (auquel cas chaque point commence par une majuscule et termine par un point). Le mélange des deux n'est par contre pas permis.:)
> Correction of a little inconsistency

- src/q6/prostoch-INMA1731/summary/prostoch-INMA1731-summary.tex
A mon avis, @peiffap l'avait déjà préparé dans une de ses prochaines PRs.
> Summary INMA1731 - Fix wrong title

- src/config.yml
- src/q7/combu-MECA2160/combu-MECA2160.mk
- src/q7/combu-MECA2160/exam/2019/2019.mk
- src/q7/combu-MECA2160/exam/2019/Janvier/All/Makefile
- src/q7/combu-MECA2160/exam/2019/Janvier/All/combu-MECA2160-exam-2019-Janvier-All.tex
- src/q7/combu-MECA2160/exam/2019/Janvier/Janvier.mk
- src/q7/combu-MECA2160/exam/exam.mk
This applies the suggestions on #660
> Add combustion and fuels exam (Jan 2019)

- README.md
A lot of people keep creating commits on top of their *master* branch, which poses lots of problem when they want to do multiple modifications, or we squash their commits and they end up with a diverged master...
So we should probably emphasize the use of branches, hoping that people will read the documents.
> Update README.md to suggest using branches

- src/q6/mcp-INGI1122/exam/2019/2019.mk
- src/q6/mcp-INGI1122/exam/2019/Juin/Juin.mk
- src/q6/mcp-INGI1122/exam/2019/Juin/Majeure/Makefile
- src/q6/mcp-INGI1122/exam/2019/Juin/Majeure/mcp-INGI1122-exam-2019-Juin-Majeure.tex
> [INGI1122] Add exam June 2019 MAJ

- src/q6/telecom-ELEC1360/exam/2019/2019.mk
- src/q6/telecom-ELEC1360/exam/2019/Juin/Juin.mk
- src/q6/telecom-ELEC1360/exam/2019/Juin/Mineure/Makefile
- src/q6/telecom-ELEC1360/exam/2019/Juin/Mineure/telecom-ELEC1360-exam-2019-Juin-Mineure.tex
> [ELEC1360] Add exam June 2019 MIN

- src/q1/elec-EPL1201/exam/2015/Janvier/All/elec-EPL1201-exam-2015-Janvier-All.tex
- src/q1/elec-EPL1201/exam/2016/Septembre/All/elec-EPL1201-exam-2016-Septembre-All.tex
- src/q5/circ-ELEC1530/exam/2018/Janvier/Majeure/circ-ELEC1530-exam-2018-Janvier-Majeure.tex
- src/q5/circ-ELEC1530/summary/circ-ELEC1530-summary.tex
Closes #692 .
A vérifier que tout soit correct maintenant, si possible.
> Inverse american voltage sources

- src/q6/telecom-ELEC1360/exam/2019/2019.mk
- src/q6/telecom-ELEC1360/exam/2019/Juin/Juin.mk
- src/q6/telecom-ELEC1360/exam/2019/Juin/Majeure/Makefile
- src/q6/telecom-ELEC1360/exam/2019/Juin/Majeure/telecom-ELEC1360-exam-2019-Juin-Majeure.tex
Enoncé de l'examen de telecom de Juin 2019 majeure (sans solution pour le moment)
> [ELEC1360] Ajout de l'examen de Juin 2019 Maj

- src/q5/network-INGI1341/summary/network-INGI1341-summary.tex
line 320: the line seemed to indicate that the two organisation is what followed (data plane and control plane) which is not the case, so I added those for clarity
line 344: only one of the drawback of the network was put, I added what it actually does.
> small changes for clarity in chapter 2.3

- src/q6/calcu-INGI1123/exam/2018/2018.mk
- src/q6/calcu-INGI1123/exam/2018/Juin/Juin.mk
- src/q6/calcu-INGI1123/exam/2018/Juin/Majeure/Makefile
- src/q6/calcu-INGI1123/exam/2018/Juin/Majeure/calcu-INGI1123-exam-2018-Juin-Majeure.tex
- src/q6/calcu-INGI1123/exam/2018/Juin/Mineure/Makefile
- src/q6/calcu-INGI1123/exam/2018/Juin/Mineure/calcu-INGI1123-exam-2018-Juin-Mineure.tex
- src/q6/calcu-INGI1123/exam/2019/2019.mk
- src/q6/calcu-INGI1123/exam/2019/Juin/Juin.mk
- src/q6/calcu-INGI1123/exam/2019/Juin/Majeure/Makefile
- src/q6/calcu-INGI1123/exam/2019/Juin/Majeure/calcu-INGI1123-exam-2019-Juin-Majeure.tex
Résout les problèmes de #707 (pour qu'on en finisse).
> [INGI1123] Ajout examen 2019 Majeure et 2018 Maj+min

- add.sh
- src/config.yml
- src/mysmartcp.py
> Clean config.yml and add interactive add.sh

- src/q5/mmc-MECA1901/exam/2019/Janvier/Mineure/mmc-MECA1901-exam-2019-Janvier-Mineure.tex
> [MECA1901] Fix mistake in exam January 2019 MIN

- src/q7/ml-ELEC2870/summary/ml-ELEC2870-summary.tex
Btw, this summary is too short to pass the exam.
> [ELEC2870] Summary: fix typos and mistakes in some equations

- src/q5/stat-FSAB1105/exam/2017/Janvier/All/stat-FSAB1105-exam-2017-Janvier-All.tex
> [FSAB1105] Fix typo in exam January 2017

- src/q5/thermo-MECA1855/notes/parts/05_thermodynamique_vapeurs.tex
> Fix O in Van der Waals

- course_link.py
Returns the short name (e.g. info) if there is an error.
> Update course link for users without yaml

- src/q7/radiation-ELEC2795/exam/2019/Janvier/All/radiation-ELEC2795-exam-2019-Janvier-All.tex
Correction d'une erreur de formule. Source: solution session 4
> Correction erreur dans ex2

- src/config.yml
- src/q7/mads-INMA2370/exam/2020/2020.mk
- src/q7/mads-INMA2370/exam/2020/Janvier/All/Makefile
- src/q7/mads-INMA2370/exam/2020/Janvier/All/mads-INMA2370-exam-2020-Janvier-All.tex
- src/q7/mads-INMA2370/exam/2020/Janvier/Janvier.mk
- src/q7/mads-INMA2370/exam/exam.mk
- src/q7/mads-INMA2370/mads-INMA2370.mk
> Ajout de l'examen de INMA2370 MADS de janvier 2020

- course_link.py
Remember to actually test this kind of stuff on a real system before merging...
> Fix wrong except + #681

- src/q8/translators-INGI2132/summary/translators-INGI2132-summary.tex
> [INGI2132] Remove chapters

- src/q6/calcu-INGI1123/exercises/calcu_tp5.tex
> [INGI1123] Fix line break in APE

- src/q4/circmes-ELEC1370/summary/circmes-ELEC1370-summary.tex
> correction triphasé

- src/q8/crypto-ELEC2760/summary/crypto-ELEC2760-summary.tex
> [LELEC2760] Typos and some Fix

- src/q7/ia-INGI2261/summary/ia-INGI2261-summary.tex
Simple changes to the first few pages to make the summary more readable & comprehensible.
> [INGI2261] Grammar and spelling fixes

- README.md
> Update pdf link in README

- src/q7/algo_complexity-INMA2111/algo_complexity-INMA2111.mk
- src/q7/algo_complexity-INMA2111/exam/2015/2015.mk
- src/q7/algo_complexity-INMA2111/exam/2015/Juin/All/Makefile
- src/q7/algo_complexity-INMA2111/exam/2015/Juin/All/algo_complexity-INMA2111-exam-2015-Juin-All.tex
- src/q7/algo_complexity-INMA2111/exam/2015/Juin/Juin.mk
- src/q7/algo_complexity-INMA2111/exam/2016/2016.mk
- src/q7/algo_complexity-INMA2111/exam/2016/Juin/All/Makefile
- src/q7/algo_complexity-INMA2111/exam/2016/Juin/All/algo_complexity-INMA2111-exam-2016-Juin-All.tex
- src/q7/algo_complexity-INMA2111/exam/2016/Juin/Juin.mk
- src/q7/algo_complexity-INMA2111/exam/2017/2017.mk
- src/q7/algo_complexity-INMA2111/exam/2017/Juin/All/Makefile
- src/q7/algo_complexity-INMA2111/exam/2017/Juin/All/algo_complexity-INMA2111-exam-2017-Juin-All.pytxcode
- src/q7/algo_complexity-INMA2111/exam/2017/Juin/All/algo_complexity-INMA2111-exam-2017-Juin-All.tex
- src/q7/algo_complexity-INMA2111/exam/2017/Juin/Juin.mk
- src/q7/algo_complexity-INMA2111/exam/2020/2020.mk
- src/q7/algo_complexity-INMA2111/exam/2020/Juin/All/Makefile
- src/q7/algo_complexity-INMA2111/exam/2020/Juin/All/algo_complexity-INMA2111-exam-2020-Juin-All.tex
- src/q7/algo_complexity-INMA2111/exam/2020/Juin/Juin.mk
- src/q7/algo_complexity-INMA2111/exam/exam.mk
Je propose ici mes solutions aux examens du cours LINMA2111 (Discrete mathematics II - Algorithms and complexity) de 2015, 2016, 2017 et 2020. Je suis ouvert à toute remarque :))
> Solutions examens LINMA2111 (2015->2020)

- README.md
Ajoute une mention explicite et transparent du rôle de maintainer dans le README et un appel à de nouveaux maintainers!
cc @Gp2mv3 @MartinBraquet @Peiffap @Jimvy
> Appel aux maintainer dans le README

- src/q2/chimie-EPL1301/Titrage-AB.py
Python script to calculate all there is to calculate in a Acide-Base reaction.
> Added Titrage-AB.py to Chimie 1 [LEPL1301]

- src/q8/crypto-ELEC2760/exam/2019/Juin/All/crypto-ELEC2760-exam-2019-Juin-All.tex
Not sure about everything but the idea should be there.
> [ELEC2760] Solutions examen Juin 2019

- src/q2/methodnum-EPL1104/summary/methodnum-EPL1104-summary.tex
Méthode du point fixe et systèmes linéaires : 
- Jacobi : x_{i+1}=...b => x_{i+1}=D^{-1}b
- Gauss-Seidel : x_{i+1}=...b => x_{i+1}=...(D+L)^{-1}b
> Fix typo in LEPL1104 summary

- src/q1/meca-EPL1201/exam/2017/Janvier/All/meca-EPL1201-exam-2017-Janvier-All.tex
Fix issue #902 
Automatic linting of the file
> FIX EPL1201 | exam 2017 | Typo + linting
