src/q4/os/os.tex

Correction dans le cours d'OS Unix d'une typo classique sur le nom du signal d'alarme.
Il ne contient qu'un seul A.

Fix typo SIGALRM

---

src/eplbase.cls

This isn't loaded by default with tikz since it might break some really old code. It didn't cause any regression on my machine while allowing some documents that uses circuitikz to compile.

Fix some clashes between tikz and babel

---

src/q6/telecom-ELEC1930/summary/telecom-ELEC1930-summary.tex

- Correction de la fréquence instantanée section 4.3 => Il manquait une intégrale et une parenthèse de trop
- Rajout de la définition d'EIRP section 3.5 => surement vu à partir de cette année

LELEC1930 Corrections et rajout d'une définition

---

src/q4/os-SINF1225/summary/os-SINF1225-summary.tex

Quelques corrections dans l'ensemble du document : 
* fautes de grammaire/orthographe;
* tableau trop long;
* syntaxe latex.
Il faudrait changer aussi le code du cours: c'est [1252](http://www.uclouvain.be/cours-2015-SINF1252), pas [1225](http://www.uclouvain.be/cours-2015-SINF1225). Mais je ne suis pas sûr comment faire ça sans bousiller le repo :stuck_out_tongue_winking_eye:.

Corrections Synthèse Q4 SINF1252 OS

---

src/q5/network-INGI1341/summary/algorithm/AIMD_in_tcp.py

Le dernier else (dupacks=0) est lié au if tcp.ack==snd.una au lieu du if dupacks==3

Correct de l'indentation du dernier else

---

src/q6/calcu-INGI1123/summary/calcu-INGI1123-summary.tex

Erreurs dans les démonstrations suivantes : 
* K non récursif grâce au théorème du point fixe (petite erreur de raisonnement);
* Théorème de Rice grâce au théorème du point fixe (mauvais énoncé du théorème dans sa version plus forte).
Pour plus de détails, voir la description des 2 commits :)

LINGI1123 - Calculabilité et Complexité - Petites erreurs dans 2 démonstrations

---

src/q3/math-FSAB1103/summary/math-FSAB1103-summary.tex

cosh(x)= (exp(z) + exp(-z))/2 et pas (exp(z) + exp(iz))/2

Correction d'une erreur dans la formule de cosh(x)

---

README.md
src/eplformulaire.cls

Ce commit corrige une petite erreur dans le readme ainsi que la
traduction du mot formulaire, comme discuté dans l'issue #473.

Fix erreur dans README.md et fix #473

---

src/eplcommon.sty
src/q4/edo-MAT1223/summary/edo-MAT1223-summary.tex
src/q5/stat-FSAB1105/summary/stat-FSAB1105-summary.tex
src/q6/prostoch-INMA1731/summary/prostoch-INMA1731-summary.tex

Fix the multiplicity of myprop in eplcommon; fixed some more formatting
in edo (didn't take the class though so can't say that much about the
math); found an issue in probastat and prostoch with the \N command.
Since I redefined it earlier to denote the set of natural numbers, it
became a doubly-defined command which LaTeX can't deal with. The issue
might reappear in other documents, will have to scourge the repo to find
out...

Fix myprop, formatting in edo & issue in proba/prostoch

---

src/q3/chimie-FSAB1302/exam/2015/Janvier/All/chimie-FSAB1302-exam-2015-Janvier-All.tex

@Peiffap J'ai une erreur disant que looseness n'est pas une option valide avec la dernière version de endiagram (i.e. v0.1d) et avec ce changement (qui correspond à comment looseness est utilisé dans [la doc](http://ctan.triasinformatica.nl/macros/latex/contrib/endiagram/endiagram_en.pdf)) ça marche. Chouette diagramme en tout cas :)

[FSAB1302] Fix looseness error

---

src/eplexercises.cls
src/epltest.cls

As it contains work by professors and teaching assistants.

Removing CC-BY-SA license for tests and exercises solutions

---

README.md

Le Drive est maintenant sur mon compte car l'ancien hébergeur a terminé ses études.

Update link to PDF's docs

---

src/q3/math-FSAB1103/exam/2018/Janvier/All/math-FSAB1103-exam-2018-Janvier-All.tex

J'ai visiblement du mal parfois ^^
Comme indiqué dans le commit, il y a quelques bugs avec les environnements solfig et solution qui font que la figure n'est pas parfaitement centrée dans le document produit, ainsi qu'un overfull hbox.
Je vais voir si c'est facilement réparable, ce n'est que cosmétique. J'ai aussi #396 qui m'attend.
(Fun fact: pour tester, tout a été fait depuis Gitkraken, y compris la PR.)

Minor fixes to math 3 exam 2018 janvier

---

src/eplbase.cls

Le problème est dû au chargement du package `bashful` que j'avais inséré début juillet pour avoir accès aux ID et date du dernier commit. Je requiers maintenant ce package uniquement si on veut ces informations. Donc, dans la plupart du temps, le manque du package `listings` génèrera une erreur.
PS: Top 3 in terms of commits arrives soon :3rd_place_medal: 
Closes #585.

Fix issue #585

---

src/q5/stat-FSAB1105/formulaire2/stat-FSAB1105-formulaire.tex

Dans la section «Functions of Random Variables», le paragraphe
«Strictly monotonic transformation» ainsi que le deux suivants étaient
faux à cause d’une confusion entre l’inverse d’une fonction et sa
réciproque.
Dans la section «Confidence Interval» paragraphe «(Asymptotically valid)
CI for u1-u2» la variance était confondue avec l’écart-type.

[LFSAB1105] Correction formulaire 2

---

src/q5/stat-BIR1304/exam/2011/Septembre/All/stat-BIR1304-exam-2011-Septembre-All.tex

J'ai trouvé plusieurs erreurs dans la correction de l'examen de 2011.
Voici mes propositions de correction :
- Question 2 : Dans le point deux, la deuxième variance expérimentale est mal calculée (bête faute de calcul). Ce qui entraine une réponse complètement différente du point 3, puisqu'on ne rejette pas H0 dans le point 2. Il faut donc faire un nouveau test d'hypothèse pour le point 3.
- Question 3 : Ajouté des précisions dans le début de la résolution de la première question. De nouveau trouvé des fautes dans le point 2 et donc dans le point 4 avec une faute dans le degré de confiance utilisé (on utilise 0,95 alors qu'il faudrait utiliser 0,975 puisqu'on calcule une intervalle de confiance qui est par définition bilatéral).
- Toujours pour la question 3, j'ai changé l'utilisation des …

BIR1304 - Correction de la correction d'examen

---

src/eplcommon.sty

Il me semble qu'il y a une petite faute de frappe dans le template, `d\frac` au lieu de `\dfrac`

Correction de la commande fdpart{f}{x}{y}

---

src/q4/os-SINF1252/exam/2017/Juin/Majeure/os-SINF1252-exam-2017-Juin-Majeure.tex

Correction de l'algorithme de Peterson, la condition du while devrait être un && et non un ||

[LSINF1252] Correction exam Juin 2017

---

src/q4/circmes-ELEC1370/exam/2013/Juin/Majeure/circmes-ELEC1370-exam-2013-Juin-Majeure.tex
src/q4/circmes-ELEC1370/exam/2013/Juin/Mineure/circmes-ELEC1370-exam-2013-Juin-Mineure.tex
src/q4/circmes-ELEC1370/exam/2014/Juin/Majeure/circmes-ELEC1370-exam-2014-Juin-Majeure.tex
src/q4/circmes-ELEC1370/exam/2014/Septembre/All/circmes-ELEC1370-exam-2014-Septembre-All.tex
src/q4/circmes-ELEC1370/exam/2016/Juin/Majeure/circmes-ELEC1370-exam-2016-Juin-Majeure.tex
src/q4/circmes-ELEC1370/summary/circmes-ELEC1370-summary.tex
src/q4/circmes-ELEC1370/test/2017/Mars/All/circmes-ELEC1370-test-2017-Mars-All.tex

\usepackage[oldvoltagedirection]{circuitikz} everywhere in LELEC1370

[LELEC1370] voltage sign direction correction

---

src/q5/logique-INGI1101/summary/logique-INGI1101-summary.tex

Les 2 définition (preuve formelle et preuve informelle) sont inversées dans la synthèse, ca se voit/devine assez facilement, mais ce serait bête que quelqu'un l'étudie dans ce sens (CF Syllabus moodle p25)

correction definition preuve formelle/informelle

---

course_link.py

Forgot to update this file, the course title is no longer automatically rendered in hypertitle of the newly created docs.

Update course_link.py after cleaning config.yaml

---

src/q5/network-INGI1341/summary/network-INGI1341-summary.tex

In Character stuffing, the DLE is added after each DLE contained in the data of the frame and not in front. Even if in practice this remains equivalent.
(http://beta.computer-networking.info/syllabus/default/principles/reliability.html#the-datalink-layer)
The selective repeat maximum window size is not 2^(n-1) but (2^n)/2 . 
(http://beta.computer-networking.info/syllabus/default/principles/reliability.html#go-back-n-and-selective-repeat)

[INGI1341] Selective repeat buffer size & Char stuffing correction

---

src/q6/autolin-INMA1510/summary2/autolin-INMA1510-summary.tex

The 1 should be inside the square root, as can be seen on the fiches (v. 2019-05-06), section 6.2.1, on p. 11. Closes #807.

Autolin: Fix formula for amplitude of 1st order TF

---

src/q6/calcu-INGI1123/exercises/calcu_tp1.tex

if we use the previous pseudo code, instead of printing Z (0,1,-1,2,-2,...), we print 3 different 0 values at the beginning (0,0,-0,1,-1,2,-2,...).
Since we already print 0 before thhe loop and we don't want to print -0, the increment of i has to be in the beginning of the loop

correction pseudo code exo 1.3.1

---

README.md

We missed one reference, this is fixed now. Ref #823.

Uniformize doc link in README

---

README.md

Following the current link gives a drive with a file containing this new link.

Update pdf url

---

README.md

pdf-url in README.md was set to migel delcourt's onedrive and not martin's drive

Updated link to drive
